events {}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    sendfile on;

    server {
        listen 80;
        server_name nonncal.nomorepartiessite.ru;

        # API
        location /api/ {
            proxy_pass http://backend:3000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # картинки из backend
        location /content/ {
            proxy_pass http://backend:3000;
            proxy_set_header Host $host;
        }

        # весь фронт
        location / {
            proxy_pass http://frontend:80;
            proxy_set_header Host $host;
        }
    }

    server {
        listen 80;
        server_name nonncal.nomorepartiessbs.ru;

        location / {
            proxy_pass http://backend:3000;
            proxy_set_header Host $host;
        }
    }
}